# This workflow will build a package using Gradle and then publish it to Maven Central when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#publishing-using-gradle

name: Publish package to the Maven Central Repository

on:
  release:
    # see https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
    #types: [released, prereleased]
    types: [created]

jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Decode GPG private key into file
        id: write_gpg_file
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'GPG_PRIVATE_KEY.gpg'
          encodedString: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}

      - name: Decode GPG private key into path
        id: write_gpg_path
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/GPG_PRIVATE_KEY.gpg
          encodedString: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}

      - name: Decode GPG secret
        #id: base64-secret-to-file
        uses: davidSchuppa/base64Secret-toFile-action@v3
        with:
          secret: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
          filename: 'GPG_PRIVATE_KEY.gpg'
          destination-path: ${{ github.workspace }}

      - name: Read GPG file
        id: read_gpg_file
        uses: andstor/file-reader-action@v1
        with:
          #path: ${{ steps.write_gpg_file.outputs.filePath }}
          path: ${{ steps.write_gpg_path.outputs.filePath }}

      - name: Publish
        # as suggested by https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-publish-libraries.html
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
          #ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ steps.read_gpg_file.outputs.contents }}